- README.md
- UnleashClient/constants.py
- docs/index.md
- tests/utilities/testing_constants.py
Match other language versions by moving `/api` to the initialization.
The Go/Ruby/Node/Java versions all set the `/api` part in the initialization as part of the `url` parameter.
Fixes #4 
> Match other language versions by moving `/api` to the initialization.

- UnleashClient/__init__.py
Allow manual configuration of the cache directory. In cases where the Python application is run as a user without a home directory, fcache will fail. By default it will choose `~/.cache`, which will not exist.
This PR adds the ability to set the cache directory when initializing the Unleash client.
> Allow configuration of the cache directory

- UnleashClient/__init__.py
- UnleashClient/api/register.py
- UnleashClient/periodic_tasks/send_metrics.py
- docs/changelog.md
- tests/unit_tests/periodic/test_aggregate_and_send_metrics.py
```
We have been running the new code in production for a week now, and the problem with the false bucket start time is gone. Unfortunately we have ran into another problem. The timestamps generated by datetime.now() is in local time without timezone information, and when sent to the Unleash server it will assume they are in UTC (at least our instance of the server will).
```
Fixed w/minor modification of Calle's code. :)
> Fixes issue where datetimes are sent w/out timezone.

- UnleashClient/__init__.py
- UnleashClient/api/features.py
- UnleashClient/api/metrics.py
- UnleashClient/api/register.py
- UnleashClient/periodic_tasks/fetch_and_load.py
- UnleashClient/periodic_tasks/send_metrics.py
- tests/unit_tests/api/test_feature.py
- tests/unit_tests/api/test_metrics.py
- tests/unit_tests/api/test_register.py
- tests/unit_tests/periodic/test_aggregate_and_send_metrics.py
- tests/unit_tests/periodic/test_fetch_and_load.py
- tests/unit_tests/test_client.py
- tests/utilities/testing_constants.py
* For on-premises Unleash servers, having the ability to bypass or override SSL certificate verification is convenient. This update allows us to forward custom kwargs to `request.post` during client registration to allow for these kinds of customizations
* Also, refactored relevant unit tests to reduce code duplication
> Add ability to forward request kwargs

- UnleashClient/__init__.py
- UnleashClient/deprecation_warnings.py
- UnleashClient/features/Feature.py
- UnleashClient/strategies/Strategies.py
- UnleashClient/utils.py
- pytest.ini
- tests/unit_tests/test_custom_strategy.py
- tests/utilities/mocks/mock_custom_strategy.py
- tests/utilities/old_code/StrategyV2.py
- On client initialization, compare the `__call__` method on custom strategies to the `__call__` method on the base Strategy object (which is basically just a warning) for all custom strategies.  If they are different (i.e. an old custom strategy), show a DeprecationWarning.
- Add unit tests to ensure a) we're throwing the warning and b) features with old invalid custom strategies return appropriate values.
> Add deprecation warning if folks try to use old Custom Strategies

- .github/workflows/pull_request.yml
Add the `pull_request_target` event to the standard CI/CD workflow.
> Fix Github Actions for PRs from a forked repo

- UnleashClient/api/metrics.py
- docs/changelog.md
Log errors from submitting metrics (i.e. due to timeouts) as `warnings` and not `exceptions`.  As metrics are a reporting function, this feels like a more appropriate log level. :)
I'm leaving the feature and registration logging alone since those are much more important to UCP.
Fixes #122 
> Log errors from submitting metrics as warnings and not exceptions.

- .bumpversion.cfg
- UnleashClient/constants.py
- docs/changelog.md
- setup.py
Changes:
* (Minor) Add Python 3.9 support.
* (Minor) Only log errors generated when strategy loading fails once.
* (Minor) Errors submitting metrics will be logged as warnings and not exceptions.
* (Minor) Update apscheduler version to 3.7.0
> rc for v3.6.0

- UnleashClient/loader.py
- tests/unit_tests/test_loader.py
When the new features are downloaded, the loader first updates the file cache before updating
the in-memory cache.
This PR attempts to fix an issue where the loader did not properly update the variants part of the cache.
This caused the variants to be stale until the next cache initialisation on client restart.
> Fix issue with updating in-memory variants in the loader

- UnleashClient/__init__.py
This does not do what you think.
Defaulting to a dict will default the **same** dict for every call of that function.
Read about mutable defaults, a common python mistake:
- https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments
Creating the dict inside the function and not inside the method definition ensures a new empty dict every time.
This is especially important for `is_enabled`'s  context, since the library modifies it.
> client: don't use mutable defaults

- UnleashClient/features/Feature.py
- UnleashClient/strategies/Strategy.py
- tox.ini
This fixes two instances of Pylint warning about ‘R1729: Use a generator
instead’.
It also adds pylint to tox.ini, to keep it in sync with the tox-osx.ini
file, and with the Github Actions setup.
> Fix Pylint ‘R1729: Use a generator instead’ warnings

- Makefile
- UnleashClient/strategies/FlexibleRolloutStrategy.py
- UnleashClient/variants/Variants.py
- docs/changelog.md
- tests/specification_tests/test_11_strategy_constraints_edge_cases.py
- tests/specification_tests/test_12_custom_stickiness.py
- tests/unit_tests/strategies/test_flexiblerollout.py
- tests/unit_tests/test_variants.py
- tests/utilities/mocks/mock_variants.py
Adds support for custom stickiness on `FlexibleRollout` strategy and variants.
#145 
Fixes: #144, #145
> Client support for custom stickiness

- .github/workflows/pull_request.yml
- UnleashClient/strategies/FlexibleRolloutStrategy.py
- UnleashClient/variants/Variants.py
- tests/specification_tests/test_10_flexible_rollout.py
* #145 inadvertently introduced intermittent failures in FlexibleRollout strategy and Varient specification tests when context field (i.e. `userId`) was not present in the context.  (Basically, it would "fall through" to random seed instead of erroring and receiving the default value).
* If the API does not have a stickiness level, we will default to `default`.
* CI on PR should run against the PR branch, not the pull request target. 🤦 
> Fix issues introduced by custom stickiness support!

- README.md
This to comply with v4 requirements.
> fix: add authorization headers to getting started example

- setup.py
Installing unleash-client-python currently installs a "tests" package to site-packages, which causes issues for running unit-tests locally in projects that use the unleash client.
Stop publishing tests folder
Run  make build-local.  Check if tests folder is excluded in dist/UnleashClient-4.2.0-py2-none-any.whl & dist/UnleashClient-4.2.0.tar.gz
> Exclude test package from dist & wheel

- README.md
- UnleashClient/__init__.py
- docs/changelog.md
- docs/unleashclient.md
- tests/integration_tests/integration_unleashhosted.py
Allows users to configure log level of verbose messaging (mainly around failures to check feature flags or varients).
Fixes #150 
> Configure log level of verbose messages

- UnleashClient/__init__.py
- docs/unleashclient.md
- tests/unit_tests/test_client.py
The
```
with UnleashClient(...) as client:
client.is_enabled(...)
```
idiom is very pythonic. It reduces the code size over the current
explicit initialization and destruction and ensures the client will be
destroyed even if there are exceptions during its lifetime (i.e, the
user's program fails before destroying its client).
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
> Allow to run unleash clients as context managers

- MANIFEST.in
- setup.py
This marks the package as ‘typing friendly’ and enables tools like mypy
to actually type check code using this library.
Closes #161.
> Include py.typed marker in sdist/wheel packages

- README.md
This is just a documentation update that provides some context for easy to fall into traps for running the client in wsgi
> docs: Add some details for running the client under wsgi

- README.md
This is just a patch to the docs to reference the Flask SDK project, which consumes this project. We're looking to doing this because we've had a number of people get great value out of that project and then ask why the docs here didn't point to it
> docs: Link to flask sdk in docs

- .bumpversion.cfg
- UnleashClient/constants.py
- docs/changelog.md
- setup.py
Changelog:
```
* (Breaking) Modify client initialization to allow jitter configuration on refresh/background refresh intervals.  May break code when parameters to UnleashClient are not used as keyword arguments.  Thanks @dryobates and @jstolarski!
* (Major) If client is already initialized, calling `initialize_client()` again won't re-run initialization.
* (Minor) Support HTTP 304 on `/client/feature` endpoint.
* (Minor) Rename `master` to `main`.
* (Documentation) Document running UnleashClient in uWSGI.  Thanks @sighphyre!
* (Documentation) Fix links and formatting.  Thanks @thomasheartman & @sighphyre!
```
> Prepare for v5.0.0 release

- UnleashClient/api/features.py
As mentioned in #185 the client should not attempt to parse 
the request body if the returned http status code was 304 as 
servers like gitlab send an empty response body in this case.
The result from get_feature_toggles gets ignored in
fetch_and_load_features if None is returned.
Fixes #185 
> fix: do not try to parse unmodified feature flags

- CHANGELOG.md
- UnleashClient/utils.py
During #197 investigation found that Unleash wasn't printing log messages correctly.  This PR:
* Fixes that whoops. >_<
* Moves `UnleashClient` logging to it's own logger.
> Fix logging in UCP.

- UnleashClient/__init__.py
Usually Unleash Python SDK would do 2 things periodically:
1. fetch feature toggles from the Unleash server,
2. load them into the local [Cache](https://github.com/Unleash/unleash-client-python/blob/4c7bc98e7919f5f3ae91ca1c732337be61b2d17b/UnleashClient/cache.py#L7).
Then SDK uses the toggles from the cache.
However, when a service (or application) is using multiprocessing for concurrency, such model creates higher loads on Unleash than ideal:
1. now each separate process has it's own cache and is fetching the toggles. This is somewhat touched at https://github.com/Unleash/unleash-client-python/issues/105
2. Instead, we'd like one process to fetch the toggles and other process load them.
To cater such concurrency models this PR allows to run Unleash SDK in 2 modes:
1. The regular way: …
> 2 modes for running Unleash integration

- README.md
- docs/usage.rst
This PR adds the following changes to the readme file:
- Toggle names are changed to remove spaces. Unleash doesn't support spaces in feature toggle names (names must be url-friendly), so I've instead lowercased them and used underscores as their separators.
- Replace the `default_value` example with two examples of using `fallback_function`: one with a named function, and one with a lambda to replace the `default_value`.
This has some relation with #207 and #100. It doesn't close any issues (as far as I'm aware), but it does seem to be some leftover changes that were just never cleaned up.
I am, of course, happy to make any changes to the PR if you have any suggestions.
> docs(readme): update `default_value`, fix toggle naming

- docs/celery.rst
- docs/index.rst
Adds documentation on how to get this project working with Celery
> docs: add a section on getting the client working with celery

- UnleashClient/api/features.py
- UnleashClient/constants.py
- tests/unit_tests/api/test_feature.py
Create session and provide it with a custom HTTPAdapter, that has max_retries set.
Fixes #217 
> Add retries to get features

- .github/workflows/pull_request.yml
- CHANGELOG.md
- UnleashClient/cache.py
* Fixes new lint error in CI/CD by adding timeout to cache bootstraping.
* Attempts to only run notifications on PRs from not-forks (otherwise people's good PRs fail b/c they don't have access to webhook).
> Small fixes

- UnleashClient/__init__.py
- pyproject.toml
- tests/unit_tests/test_client.py
Fixes #221
* Allows users to pass in a custom APScheduler `scheduler` and specify the executor type.
* If no customized `scheduler` is provided, spin up an scheduler with a Unleash-specific pool name.
> Allow customization of  APScheduler

- requirements.txt
- setup.py
This moves the murmur hash library to https://github.com/Fokko/mmhash3. The original mmh3 library hasn't been maintained in 2 years and does not have prebuilt wheels for Python 3.10+, which is causing pain for users.
> move to mmhash3 library

- UnleashClient/__init__.py
- UnleashClient/api/features.py
Looks like Pylint got an update and it's now flagging code that's been around for a while. I would agree with these warnings for new code but the stuff that's being flagged is and has been working for a while. I'm proposing we disable these
> chore: disable a few new pylint warnings

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/post_install.sh
- .github/workflows/pull_request.yml
- UnleashClient/__init__.py
- UnleashClient/api/features.py
- UnleashClient/events.py
- docs/development.rst
- docs/events.rst
- docs/index.rst
- docs/strategy.rst
- requirements.txt
- setup.py
- tests/unit_tests/test_client.py
- tests/utilities/mocks/mock_features.py
- tox.ini
* Add impression events support.
* Use `blinker` as an example implementation.
* Add devcontainer for local/Codespace development.
* Support Python 3.11 in tests.
* Remove Slacks for PRs so forks don't fail.
Fixes #238 
> Impression events for ucp

- UnleashClient/features/Feature.py
- UnleashClient/periodic_tasks/send_metrics.py
- tests/unit_tests/periodic/test_aggregate_and_send_metrics.py
- tests/unit_tests/test_features.py
This change adds most variant metrics functionality to the Python SDK.
Variant metrics should be counted whenever get_variant is called:
- if a feature doesn't have variants, register the disabled variant
- if a feature is disabled, register the disabled variant
- otherwise, register the variant that was returned
There is one piece of functionality that isn't included in this PR:
- if a feature doesn't exist, it should still register the disabled variant.
As far as I can tell, this SDK doesn't count metrics for toggles that don't exist, so there was no obvious way to add variant metrics for these features. Both of those cases will be implemented in a follow-up PR.
When serializing metrics, I have done the simple thing and added the variant counts dict, regardless of whether it is empty or …
> feat: add variant metrics

- UnleashClient/cache.py
Typo in `Cache` doctstrings
Documentation
N/a
> docs(cache): fix typo in docstrings

- tests/unit_tests/api/test_feature.py
This PR skips the test that's currently failing until July 1st. We suspect the reason it's failing is because of a dependency and/or something in the scaffolding. It suddenly started failing a few weeks ago. We have spent some hours looking into what's wrong, but haven't been able to fix it just yet.
> test: skip failing test

- tests/unit_tests/test_client.py
This test appears to be the **exact same** as the one right above
it (`test_uc_server_error`): copying one into the other triggers no
changes from git.
Unless I'm missing something, I suggest we remove it because it's both
confusing to have two identical tests, and because it takes 20 seconds
to sleep.
They also appear to have been the same since they were introduced in 5c9146219fd0 (almost 4 years ago).
> chore: remove duplicated test

- UnleashClient/__init__.py
- UnleashClient/features/Feature.py
- UnleashClient/loader.py
- tests/unit_tests/test_client.py
This PR is the follow-up to #253 and makes the client track metrics for features that don't exist.
It achieves this by modifying the Unleash client's `is_enabled` and `get_variant` methods:
Whenever they are called with a feature that doesn't exist, we create a new feature with that name, `enabled = False`, no strategies, and no variants. The feature gets added to the clients list of features, and is then queried for its state (to track metrics; we know it'll be false).
The tests ensure that metrics are sent for these nonexistent features, but does not care about the implementation, so we should be able to change that as much as we want later.
I've been back and forth a couple of times regarding how best to track these features. Because the `send_metrics` function already takes care of …
> Count metrics for non-existing features

- tests/unit_tests/api/test_feature.py
- tests/unit_tests/test_features.py
No logic changes here, this just updates a check in the tests to not make the linter sad so that the build works
> fix: small patch to make linter happy on main

- UnleashClient/constraints/Constraint.py
- tests/unit_tests/test_features.py
For better discussion about https://github.com/Unleash/unleash-client-python/issues/266
> fix: make check_date_operators work with dateutil < 2.8.1

- tests/unit_tests/api/test_feature.py
It was brought up in https://github.com/Unleash/unleash-client-python/issues/275 that a test was failing. The reason appears to be because the response was passing `{}` back in a 304 which requests doesn't like. This behavior is consistent with [RFC 7232 - 4.1 304 Not Modified](https://datatracker.ietf.org/doc/html/rfc7232#section-4.1) i.e. a 304 should not have a body. Another way to confirm this is the root cause is to note the exception
```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(2 bytes read, -2 more expected)', IncompleteRead(2 bytes read, -2 more expected))
```
points out it read two bytes (`{}`) but expected nothing.
Fixes https://github.com/Unleash/unleash-client-python/issues/275
Please describe …
> fix: update responses mock for etag test

- UnleashClient/constraints/Constraint.py
- pyproject.toml
Add support for semver 3 while maintaining backwards compatibility with semver 2
#276 
I ran the unit tests with both version of the semver package 2.13.0 and 3.0.2
> Support semver 3

- UnleashClient/__init__.py
- UnleashClient/api/features.py
- UnleashClient/api/metrics.py
- UnleashClient/api/register.py
- UnleashClient/periodic_tasks/fetch_and_load.py
- UnleashClient/periodic_tasks/send_metrics.py
- tests/unit_tests/api/test_feature.py
- tests/unit_tests/api/test_metrics.py
- tests/unit_tests/api/test_register.py
- tests/unit_tests/periodic/test_aggregate_and_send_metrics.py
- tests/unit_tests/periodic/test_fetch_and_load.py
- tests/unit_tests/test_client.py
- tests/utilities/testing_constants.py
Configurable request timeout and retry count. Added the new params at the end of all param lists before the default params (in all relevant methods).
I compared Python SDK config options to Node SDK and timeout is present in Node SDK. So adding it here should be a non-issue. Retry config is not available in Node but I see no harm in exposing it here.
Closes https://github.com/Unleash/unleash-client-python/issues/290
> feat: configurable timeout and retries

- CHANGELOG.md
Fixes an issue where the linter would fail on changelog because of trailing whitespace
> fix: remove trailing whitespace

- .github/workflows/pull_request.yml
- UnleashClient/features/Feature.py
- tests/unit_tests/test_client.py
- tests/utilities/mocks/mock_features.py
This PR fixes an issue where parent flags would have metrics counted when you call `get_variant` on a child flag. This was due to a missing `skip_stats` argument in the `get_variant` method of a feature.
I have added a test and the specific data setup that was reported to cause the issue.
> fix: don't count stats for parent flags, even in get_variant

- UnleashClient/__init__.py
- tests/unit_tests/test_client.py
This PR fixes a bug where we didn't count metrics correctly: if the dependencies were not satisfied during a `get_variant` call, we wouldn't track any metrics for the flag at all. During an `is_enabled` call, we'd track the result of the child flag's evaluation without taking into account the dependencies.
Note that the **behavior** was still correct. This is only about metrics.
The root cause is related to how we check dependencies and act on that result: the Unleash client checks dependencies as part of its `is_enabled` and `get_variant` calls, but the metrics are tracked in the individual `Feature` objects.
The current implementation was the quickest way I could fix the issue. I think we should restructure it (probably; either now or later) to avoid calling internal methods of the …
> fix: correctly count metrics when a flag with dependencies has disabled parents

- Makefile
- pyproject.toml
- tests/unit_tests/test_custom_strategy.py
Ruff got an upgrade, the old `ruff <path>` command we use in the build no longer works. Now apparently it wants `ruff check <path>`
This new version of Ruff also raises a new lint, which is fixed in this PR.
Bonus points for fixing Ruff config in pyproject.toml that had been raising some warnings for some time
The build
This PR + build pipeline
> chore: adapt ruff call in build to new format

- UnleashClient/api/register.py
- UnleashClient/periodic_tasks/send_metrics.py
- tests/unit_tests/api/test_register.py
- tests/unit_tests/periodic/test_aggregate_and_send_metrics.py
Adds metadata to registration and metrics, this doesn't affect the public API or internal workings, really, it just allows the Unleash server to get better insights into what the connected SDKs are up to in the wild
> feat: add metrics metadata

- .github/workflows/release-package.yml
`install-docs` lives in the root makefile, not in the docs makefile
> chore: fix docs build

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .github/workflows/pull_request.yml
- docs/development.rst
- pyproject.toml
- tox.ini
Drops support for the now EOL Python3.7 (which is causing some issues with build tooling on the Yggdrasil side). Formally support Python 3.13. Cleans up some references around Python3.6 (long gone) and Python 3.12 (should have been in, were missing)
> chore: drop support for python3.7, support python3.13

- UnleashClient/constraints/Constraint.py
- tests/unit_tests/test_constraints.py
- tests/utilities/mocks/mock_constraints.py
The Unleash web app provided timezone info when creating date constraints so this PR updates the client to also provide timezone info for datetime objects it creates. And then gracefully fall back to UTC if an ISO string is received with no timezone info. 
Fixes #323
> Safely handle datetime constraint values with and without timezone info

- UnleashClient/__init__.py
- tests/unit_tests/test_client.py
- tests/utilities/mocks/mock_features.py
This converts all values in the context object into their representative string type before sending it to Yggdrasil.
Also adds the current time property if not set. This was previously set in the constraints code, which no longer exists
> chore: safe context

- .devcontainer/devcontainer.json
- .github/workflows/release-package.yml
- Makefile
Use [PyPi's official Github Action](https://docs.pypi.org/attestations/producing-attestations/) for more secure publishing & attestations.
> Use PyPi Publish Github actions

- UnleashClient/__init__.py
- tests/unit_tests/test_client.py
x- headers are deprecated (https://datatracker.ietf.org/doc/html/rfc6648). Let's use unleash- instead.
> fix: drop x prefix

- .github/workflows/release-package.yml
removes the slack notifier for github as we do not use it.
> chore: remve gh-action slack notify

- UnleashClient/__init__.py
- UnleashClient/api/register.py
- UnleashClient/periodic_tasks/send_metrics.py
- tests/unit_tests/api/test_metrics.py
- tests/unit_tests/api/test_register.py
- tests/unit_tests/periodic/test_aggregate_and_send_metrics.py
- tests/unit_tests/test_client.py
- tests/utilities/mocks/mock_metrics.py
- tests/utilities/testing_constants.py
- Fetch flag calls include the `unleash-interval` header.
- Registration calls now have `connectionId` added to the payload (previously, it only had the `unleash-connection-id` header).
- Send metrics calls include the `unleash-interval` header.
- Send metrics now have `connectionId` added to the payload (previously, it only had the `unleash-connection-id` header).
> feat: new headers and payload ( connection id and interval)

- Makefile
- UnleashClient/__init__.py
- UnleashClient/api/features.py
- UnleashClient/api/metrics.py
- UnleashClient/api/register.py
- requirements.txt
- tests/unit_tests/test_client.py
UnleashClient's `destroy()` function was just unregistering the metrics job and not flushing metrics.  This can lead to up to N seconds where N = metrics job interval of metrics to get lost.  
Changes:
- If metrics are enabled, `destroy()` will try and flush metrics after metrics job is unscheduled (to avoid dupes).
- Light refactoring to share code between initialize/destroy functions.
- Add error code for when API calls fail to make troubleshooting easier.
> Flush metrics on destroy

- UnleashClient/__init__.py
- UnleashClient/events.py
- UnleashClient/loader.py
- UnleashClient/periodic_tasks/fetch_and_load.py
- tests/unit_tests/test_client.py
Adds in events for when features are fetched and when the SDK becomes ready.
This brings us more inline with the other SDKs which have these events at minimum.
Closes #356
> feat: events

- .devcontainer/post_install.sh
- CONTRIBUTING.md
- README.md
- docs/conf.py
- docs/usage.rst
- pyproject.toml
The repository was renamed from unleash-client-python to unleash-python-sdk. This PR updates all references to the repository (except for CHANGELOG.md).
Because the artifact remains unchanged, that's all we need to update.
- Documentation: code remains unchanged
N/A
> chore: update references to new repo name

- UnleashClient/api/register.py
Allow 200 response code to pass registration.
Without this, a Python UnleashClient cannot register appropriately:
```
from UnleashClient import UnleashClient
client = UnleashClient(
url="https://gitlab.com/api/v4/feature_flags/unleash/123",
app_name="ci",
instance_id="abcde")
client.initialize_client()
print(client.is_enabled("dummy_flag"))
```
Created a small UnleashClient(...) script (see above), and checked it passes.
> Update register.py: Allow 200 response code

- UnleashClient/__init__.py
- tests/unit_tests/test_client.py
Send the client spec version when fetching features. This is important because it allows the Unleash server to know that it can send segments as standalone entities. This means better compression on the sending of features - better for the client and better for the server
> fix: send client spec version when fetching features

- tests/unit_tests/test_client_streaming.py
The streaming tests currently attempt to tear down all running threads. Which is a pity because a bunch of tests in the SDK leave their background threads alive, expecting process exit to terminate those. They also don't respect the streaming tests' attempt to tear them down so they wait until the test harness times out. 
This means that running the whole test suite takes 10 minutes
This just throws that tear down away. There's no reason for it - looks like runaway ChatGPT
> chore: remove the global thread tear down in the streaming tests
