- .circleci/config.yml
- Pipfile
- Pipfile.lock
- UnleashClient/__init__.py
- UnleashClient/api/features.py
- UnleashClient/loader.py
- tests/unit_tests/periodic/test_fetch_and_load.py
Since there's still a lot of Python 3.5 being used in the community, including us, we've taken the opportunity to make the python client compatible with Python 3.5.
Fortunately there wasn't a lot of code making use of newer language features, so the impact is relatively low. The test coverage is excellent, so the few things that did need to change were easy to spot.
- [ x] New feature (non-breaking change which adds functionality)
All existing tests have been run and pass
- [x ] Unit tests
- [ x] Spec Tests
- [ x] Integration tests / Manual Tests
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings
- [ x] New and …
> Support python 3.5

- .bumpversion.cfg
- UnleashClient/constants.py
- setup.py
> Automatic version bump via bumpversion.

- MANIFEST.in
Add manifest file to fix Python 3.5 install/build issue.
> Add manifest file.

- README.md
- UnleashClient/__init__.py
- UnleashClient/constants.py
- UnleashClient/loader.py
- pylintrc
- setup.py
- tests/unit_tests/test_client.py
- tests/utilities/decorators.py
- tests/utilities/mocks/mock_features.py
- tests/utilities/testing_constants.py
> feat: add support static context fields

- UnleashClient/loader.py
- UnleashClient/periodic_tasks/fetch_and_load.py
- docs/changelog.md
- docs/index.md
- tests/integration_tests/integration.py
- tests/unit_tests/test_client.py
Add error handling to `load_features()` to handle case where no `/client/features` response is in cache.
This will happen when:
- Unleash client is initializing for the first time.
- Unleash server is not accessible.
Fixes #29 
> Better handle initialization if cache not present and Unleash server not accessible

- .circleci/config.yml
- docs/changelog.md
- setup.py
> Support Python 3.8

- .bumpversion.cfg
- UnleashClient/constants.py
- setup.py
> v3.1.0 RC branch

- UnleashClient/constraints/Constraint.py
- requirements.txt
- tests/specification_tests/test_09_strategy_constraints.py
> Custom context should be passed in the properties sub-property of the context

- README.md
- UnleashClient/__init__.py
- UnleashClient/features/Feature.py
- docs/changelog.md
- docs/index.md
- docs/strategy.md
- requirements.txt
- setup.py
- tests/unit_tests/test_client.py
> Add fallback function so users can customize default values.

- .bumpversion.cfg
- UnleashClient/constants.py
- setup.py
> Standard RC build

- README.md
- UnleashClient/__init__.py
- UnleashClient/constants.py
- UnleashClient/constraints/Constraint.py
- UnleashClient/features/Feature.py
- UnleashClient/loader.py
- UnleashClient/utils.py
- UnleashClient/variants/Variants.py
- UnleashClient/variants/__init__.py
- docs/changelog.md
- docs/index.md
- tests/integration_tests/integration_unleashhosted.py
- tests/specification_tests/test_01_simple_examples.py
- tests/specification_tests/test_08_variants.py
- tests/unit_tests/test_client.py
- tests/unit_tests/test_custom_strategy.py
- tests/unit_tests/test_features.py
- tests/unit_tests/test_loader.py
- tests/unit_tests/test_variants.py
- tests/utilities/mocks/mock_all_features.py
- tests/utilities/mocks/mock_features.py
- tests/utilities/mocks/mock_variants.py
> Support variations

- docs/customstrategies.md
- Fixes outdated instructions.
> Fix custom strategy documentaiton.

- docs/customstrategies.md
- tests/integration_tests/integration_unleashhosted.py
* Improve Unleash Hosted troubleshooting script.
* Fixed documentation on custom Strategy implementation.
> Fix strategy import.

- .github/workflows/pull_request.yml
- .github/workflows/release.yml
- README.md
- Rename of Workflows to be slightly more descriptive.
- Update CI badge.
> Add badging and check distribution.

- UnleashClient/api/features.py
- UnleashClient/api/metrics.py
- UnleashClient/api/register.py
- UnleashClient/utils.py
- pytest.ini
- tests/integration_tests/integration_unleashheroku.py
- tests/integration_tests/integration_unleashhosted.py
- tests/unit_tests/api/test_feature.py
For feature/metric/registration API calls:
* Log info about HTTP code failures.  (i.e. due to unexpected status codes)
* Log exception information.
Also updated integration/troubleshooting scripts.
> Add better API error logging.

- UnleashClient/__init__.py
- UnleashClient/deprecation_warnings.py
- UnleashClient/features/Feature.py
- docs/changelog.md
- docs/unleashclient.md
- tests/unit_tests/test_client.py
Fixes #99.
Changes include:
* Remove `default_value` from client's `is_enabled()` method and downstream code (Feature, fallback function check).
* Updated unit tests to demonstrate how to achieve something similar with lambdas.
* Updated documentation.
> Deprecate default_value argument.

- UnleashClient/features/Feature.py
Fixes 2 typos noticed while inspecting code
minor
> Fix typos in `Feature` docstrings

- CONTRIBUTING.md
Use project name in Contributing.md (wasn't changed from the template one)
N/A
N/A
N/A
> Use project name in Contributing.md

- UnleashClient/__init__.py
- UnleashClient/api/features.py
- UnleashClient/api/metrics.py
- UnleashClient/api/register.py
- UnleashClient/constants.py
- UnleashClient/constraints/Constraint.py
- UnleashClient/features/Feature.py
- UnleashClient/loader.py
- UnleashClient/periodic_tasks/send_metrics.py
- UnleashClient/strategies/Strategy.py
- UnleashClient/utils.py
- UnleashClient/variants/Variants.py
Styling changes:
- Fixed some typos
- Fixed params in docstring being different than function definition
- Changed pylint ignores to use error names instead of error codes (e.g.`broad-except` instead of `W0703`)
- Split some long lines
- Removed redundant parentheses from class definitions
"Functional" changes:
- Added exception message to some exceptions (instead of logging `<class Exception>`, safe)
```python
>>> import logging
>>> try:
...     1/0
... except Exception as e:
...     logging.exception("1 %s", Exception)
...     logging.exception("2 %s", e)
...
ERROR:root:1 <class 'Exception'>
Traceback (most recent call last):
File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero
ERROR:root:2 division by zero
Traceback (most recent call last):
File "<stdin>", line 2, in …
```
> Fix typos and minor styling issues

- .github/workflows/pull_request.yml
- UnleashClient/constants.py
- UnleashClient/loader.py
- setup.py
- tests/unit_tests/test_loader.py
- tests/utilities/mocks/mock_all_features.py
- tox.ini
* If strategy creation fails, log exception and add to a failed strategy list in fcache.  On future refreshes, if strategy is in the failed strategy list don't log it.
* Add Python 3.9. 
> Log strategy failures once

- UnleashClient/features/Feature.py
- UnleashClient/loader.py
- docs/changelog.md
- tests/unit_tests/test_loader.py
* Rename 'variations' property from Feature object to 'variants'.  (Refactor to address root cause of #127 )
> Rename 'variations' property on Feature to 'variants'

- .github/workflows/pull_request.yml
- UnleashClient/__init__.py
- UnleashClient/deprecation_warnings.py
- docs/changelog.md
- requirements-local.txt
- requirements.txt
- setup.py
- tox.ini
* Clean up dependencies in requirements.txt.
* Deprecates Python 3.5 (mainly cleaning up some old typing).
* Deprecated `default_value` in `is_enabled()` function.
> pre-v4.0.0 chores (cleanup requirements, deprecate Python 3.5

- .github/workflows/pull_request.yml
- Makefile
- README.md
- UnleashClient/__init__.py
- UnleashClient/api/features.py
- UnleashClient/periodic_tasks/fetch_and_load.py
- docs/changelog.md
- docs/development.md
- docs/unleashclient.md
- pytest.ini
- tests/unit_tests/api/test_feature.py
- tests/unit_tests/periodic/test_fetch_and_load.py
- tests/unit_tests/test_client.py
- tests/utilities/mocks/mock_features.py
- tests/utilities/testing_constants.py
* Allow users to specify project when initializing UnleashClient.
* Use parameter when loading features.
Fixes #136 
> Add client support for projects

- UnleashClient/api/register.py
- docs/changelog.md
- docs/unleashclient.md
- tests/unit_tests/test_client.py
Raises a requests exception if registration is attempted with an invalid URL so users can decide what to do.
Fixes #154 
> Raises exception on registration if client is initialized with invalid URL

- requirements.txt
> add types-requests dependency to fix the build with mypy 0.900+

- README.md
- UnleashClient/__init__.py
- docs/index.md
- tests/unit_tests/test_client.py
- tests/unit_tests/test_custom_strategy.py
- Don't do start-up tasks if client is already initialized.
> Sanely handle multiple client initialization

- README.md
update the url of Variant documentation
> update the url of Variant documentation

- .bumpversion.cfg
- UnleashClient/constants.py
- docs/changelog.md
- setup.py
Changelog:
```
* (Bugfix) Fix HTTP 304 handling on `/client/feature` for Gitlab. Thanks @janLo!
```
> Release v5.0.1

- CHANGELOG.md
- UnleashClient/__init__.py
- UnleashClient/cache.py
- docs/basecache.rst
- docs/customcache.rst
- docs/index.rst
* Add type hints to `BaseCache` & `FileCache`.
* Add `cache_folder` back to initialization to allow non-breaking change.
* Update documentation.
> Tweaks to abstract cache logic

- .github/workflows/pull_request.yml
- CHANGELOG.md
- UnleashClient/__init__.py
- UnleashClient/constraints/Constraint.py
- UnleashClient/utils.py
- pyproject.toml
- requirements.txt
- setup.py
- tests/specification_tests/test_13_constraint_operators.py
- tests/specification_tests/test_14_constraint_semver_operators.py
- tests/unit_tests/test_client.py
- tests/unit_tests/test_constraints.py
- tests/utilities/mocks/mock_constraints.py
- tests/utilities/mocks/mock_features.py
- tox.ini
Supports new operators outlined in #191 .
> Add new constraint operators

- CHANGELOG.md
- UnleashClient/periodic_tasks/fetch_and_load.py
* Change logging (reduce level, make message clearer) if server doesn't return feature flag provisioning (304 or errors).
Fixes #199 
> Change logging if no feature flags are returned from server

- .github/dependabot.yml
- CHANGELOG.md
- UnleashClient/__init__.py
- UnleashClient/cache.py
- UnleashClient/periodic_tasks/fetch_and_load.py
- docs/filecache.rst
- docs/index.rst
- tests/unit_tests/test_client.py
- tests/utilities/mocks/mock_bootstrap.json
- Add support for bootstraping UnleashClient from dictionary, file, or url.
Fixes #203 
> Add bootstrapping

- docs/usage.rst
fix some spelling in usage.rst
> docs: fix some spelling in usage.rst

- UnleashClient/__init__.py
- UnleashClient/cache.py
Fixes #220 
Not tested since it is just a documentation update.
> Remove old bootstrapped parameter from the documentation

- .github/workflows/pull_request.yml
A tweak so folks kind enough to submit PRs won't be rewarded with slack failures.
> Try (again) to not send Slack messages on forks.

- UnleashClient/features/Feature.py
- UnleashClient/loader.py
- tests/unit_tests/test_features.py
- tests/unit_tests/test_loader.py
- tests/utilities/mocks/mock_all_features.py
- tests/utilities/mocks/mock_bootstrap.json
- tests/utilities/mocks/mock_custom_strategy.py
- tests/utilities/mocks/mock_features.py
Currently, there is no way to get answers to the question - **Whether impression data is enabled?**
The good news is that this information is provided so we can store it and use it if needed.
> feat: Extend Feature object with new attributes

- setup.py
Pin apscheduler until 4.x.x is stable.
Fixes #239 
> Pin apscheduler to < 4.0.0.

- CHANGELOG.md
- UnleashClient/cache.py
- UnleashClient/events.py
- docs/conf.py
- docs/customcache.rst
- docs/eventcallbacks.rst
- docs/events.rst
- docs/index.rst
- requirements.txt
Documentation for new event callback feature.
Fixes #238 
> Update documentation and clean up some old dependencies.

- UnleashClient/__init__.py
`UnleashClient` docstrings missing a parameter `disable_registration`.
- Update project documentation
N/a
> docs(UnleashClient): add disable_registration docstrings

- CHANGELOG.md
> v5.9.2 release

- UnleashClient/api/features.py
- UnleashClient/api/metrics.py
- UnleashClient/api/register.py
Fixes request timeout typos
Fixes https://github.com/Unleash/unleash-client-python/issues/289
> fix: typos in request timeout

- requirements.txt
> fix:mimesis pinned to 11.1.0

- CHANGELOG.md
Add a note about the bug fix that was done in the past two days.
> chore: update change log for v5.11.2

- .devcontainer/Dockerfile
- .github/workflows/pull_request.yml
- pyproject.toml
- Update CI/CD & package information for 3.12.
- Switch back to mmh3 (package updated for 3.12).
> 3.12 support

- README.md
This package doesn't seem to be maintained anymore.
Fixes https://github.com/Unleash/unleash-client-python/issues/309
Documentation update.
N/A
> Remove the mention of abandoned Flask extension

- UnleashClient/__init__.py
Changes:
- `flat` in the docs should be `flag`
> docs: fix typo in docs

- .github/workflows/release-docs.yml
- .github/workflows/release-package.yml
Add permissions so doc release step will succeed!
> Fix permissions for doc publishing.

- .github/workflows/pull_request.yml
Turns out everything was running on Ubuntu
> chore: force os specific builds to actually run on the os they specify

- README.md
Adds docs for lifecycle events
> docs: add docs for lifecycle events

- README.md
Related to suggestions in #360
> docs: standardize on 'flags' not 'toggles'

- UnleashClient/__init__.py
- UnleashClient/constants.py
- docs/development.rst
Just aligning with the new names
> chore: change registration name to unleash-python-sdk
